version: '3.4'

services:
  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"
    volumes:
    - /volumes/mongodb:/data/db
    container_name: mongo_netflix

  rabbitMQ:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "HFEWIFHWIUEGHI"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    container_name: rabbit_netflix

  postgreSQL:
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: "netflix"
      POSTGRES_USER: "jeanfernandes"
      POSTGRES_PASSWORD: "admin"
    volumes:
    - "./volumes/postgres/:/data/db"
    container_name: pg_netflix

  s3ninja:
    image: kcomlabs/s3ninja
    ports:
    - "9444:9444"
    container_name: s3_netflix