server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8200/eureka
    register-with-eureka: true

spring:
  application:
    name: filmes-core
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host:

  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix_backend