server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host:

  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix_backend