server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8200/eureka
    register-with-eureka: true

spring:
  application:
    name: hdservice
  servlet:
    multipart:
      max-file-size: 10024KB
      max-request-size: 10024KB

s3:
  access:
    key: AKIAIOSFODNN7EXAMPLE
    secret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    host: http://localhost:9444/s3
    bucket: filmes